config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticated :user do
    root :to => 'main#home'
  end
  unauthenticated :user do
    devise_scope :user do
      root :to => "main#unregistered", as: :unregistered_root
    end
  end

  get "/demo",to: "main#demo"

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
  def unregistered
  end
  def demo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def center_div args = {}, &block
		css_classes = (args.has_key?(:class)) ? args[:class] : ""
		html = content_tag :div, class:"row center-xs #{css_classes}" do
			grid md:11, lg:11,xs:12 do
				capture(&block)
			end
		end
		html.html_safe
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classi</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/demo.haml
=render "partials/demos/nav"
=center_div do
	.row.top-space.text-left
		=grid xs:10,md:3 do
			%h2.be-normal.no-margin.radius.green-sea.white-text.large-padding Resumen
			.card
				%ul
					%li
						Hoy, 
						=link_to "Examen de cálculo","#",class:"underline"
					%li.top-space
						Mañana hay que entregar
						=link_to "Resumen de la página 23","#",class:"underline"
				
		=grid xs:10,class:"col-md" do
			=render "partials/demos/publish"

app/views/main/home.haml
<h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>

app/views/main/unregistered.haml
.row.main-cover.middle-xs.center-xs.relative{style:"min-height:80%;"}
	.absolute{style:"top:3em;right:100px"}
		%nav.white-text
			=link_to "Beneficios","#beneficios",class:"slim right-space large-padding border"
			=link_to "Iniciar sesión",new_user_session_path,class:"slim large-padding border"
	=grid xs:10,sm:8,lg:6 do
		%h1.be-big.white-text.bold.no-margin 
			=image_tag "logo.png",width:60
			Classi
		%h2.white-text.slim.no-margin.be-normal
			Organiza tus clases y cursos en un solo lugar, de manera 
			%span.underline.bold simple
		=render "partials/sign_up_form"
.big-top-space#beneficios.text-center
	.row.center-xs
		=grid lg:6,xs:10,sm:8 do
			%h2.be-big.bold.red-text.text-lighten-2 Enamórate de Classi
			=render "partials/benefits"
			.border-top{style:"margin-top:3em;padding-top:2em;border-color:#999;"}
				%p Revisa nuestra clase demo para ver todos los beneficios
				=link_to "Ir al demo",demo_path,class:"btn full-width block red lighten-2 white-text"
.big-top-space.large-padding

app/views/partials/_benefits.haml
.row.middle-xs.center-xs
	=grid xs:10,sm:6,class:"text-left col-md" do
		%h2.teal-text.underline ¿Olvidas algo?
		%p.grey-text.text-darken-2.slim 
			Deja que nosotros recordemos todo, diario te mandamos mensajes con 
			%strong todo lo que necesitas saber del día 
			de manera resumida. No volverás a olvidar tareas, material, exámenes, reuniones,
			%strong nada.
		%p Pst... tú configuras qué alertas quieres recibir y nosotros te mandamos solo esas
	=grid xs:10,sm:6 do
		=image_tag "benefits/notifications.png",height:200
.row.middle-xs.center-xs
	=grid xs:10,sm:6 do
		=image_tag "benefits/scores.png",height:200
	=grid xs:10,sm:6,class:"text-left" do
		%h2.teal-text.underline ¿Ya dieron las calificaciones?
		%p.grey-text.text-darken-2.slim 
			En
			%strong Classi
			mejoramos la comunicación del grupo, puedes ver tus calificaciones en tiempo real mientras el tutor/administrador/moderador las sube, incluso puedes configurar
			%strong Classi
			para recibir alertas de nuevas calificaciones en tu peril
		%p La mejor comunicación es instantánea, no vayas, no esperes, recibe tu calificación en cuanto es actualizada.
.row.middle-xs.center-xs
	=grid xs:10,sm:6,class:"text-left" do
		%h2.teal-text.underline Poderosas herramientas de comunicación
		%p.grey-text.text-darken-2.slim 
			Crea grupos internos para equipos de trabajo o amigos. Comparte archivos, realiza búsquedas, guarda mensajes y más con las herramientas de comunicación de
			%strong Classi
			con súper poderes.
		%p.grey-text.text-darken-2.slim Un chat hecho a la medida de tus necesidades
	=grid xs:10,sm:6 do
		=image_tag "benefits/communication.png",height:200
.row.middle-xs.center-xs
	=grid xs:10,sm:6 do
		=image_tag "benefits/dashboard.png",height:200
	=grid xs:10,sm:6,class:"text-left" do
		%h2.teal-text.underline Un feed con toda la información
		%p.grey-text.text-darken-2.slim 
			No te pierdas de nada de lo que pasa en clase, incluso sin estar ahí, el feed del grupo te dice todo, tareas, publicaciones, reuniones, notas, exámenes y más
		%p Lo organizamos y diseñamos para que lo importante esté a tu alcance de manera simple.
.row.middle-xs.center-xs
	=grid xs:10,sm:6,class:"text-left" do
		%h2.teal-text.underline Accede a tus archivos y notas desde donde sea
		%p.grey-text.text-darken-2.slim 
			No importa dónde tengas tu libreta o computadora, tus notas y archivos están a tu alcance desde cualquier equipo o dispositivo con la app.
		%p.grey-text.text-darken-2.slim Los guardamos y sincronizamos en donde tú nos digas
	=grid xs:10,sm:6 do
		=image_tag "benefits/notes.png",height:200
.row.middle-xs.center-xs
	=grid xs:10,sm:6 do
		=image_tag "benefits/integration.png",height:200
	=grid xs:10,sm:6,class:"text-left" do
		%h2.teal-text.underline Integra las apps que ya usas.
		%p.grey-text.text-darken-2.slim 
			Las fechas van en tu calendario, los archivos en tu Dropbox o Google Drive, sincronizamos tus notas con Evernote y más.
		%p
			Tenemos sincronización con más de
			%span.underline 20
			apps.
			=link_to "Revisa la sección de integraciones", "",class:"underline"

app/views/partials/_home_backup.haml
%h1.be-big.white-text.bold.no-margin 
	=image_tag "logo.png",width:60
	Classi
%h2.white-text.slim.no-margin.be-normal
	Organiza tus clases y cursos en un solo lugar, de manera 
	%span.underline.bold simple
=render "partials/sign_up_form"

app/views/partials/_sign_up_form.haml
=form_tag "/simple_sign_up", method: :post do
	.row.big-top-space
		=grid xs:10,sm:10,lg:11,class:"no-padding" do
			.form-group.white.large-padding{style:"border-radius:1em 0 0 1em;padding-left:0.5em;"}
				=text_field_tag :email, nil, required:true,class:"full-width white no-border be-normal",placeholder:"Correo electrónico"
		=grid class:"col-xs no-padding text-right" do
			=content_tag :button, type: :submit,class:"teal no-border white-text large-padding full-width",style:"padding-top:13px;padding-bottom:12px;border-radius:0 1em 1em 0" do
				%i.mi send
	%p.be-small.white-text 
		Iniciar con Classi es
		%span.bold gratis 

app/views/partials/demos/_nav.haml
%nav.large-padding.wet-asphalt.white-text.grey-text.text-lighten-3
	.row.middle-xs.center-xs
		=grid xs:6, md:1,class:"first-md text-left" do
			=image_tag "logo.png",height:30
		=grid xs:12,class:"col-md last-xs" do
			=link_to "#",class:"right-space" do
				%i.mi.md-18 home
				Home
			=link_to "#",class:"right-space" do
				%i.mi.md-18 bookmark
				Pines
			=link_to "#",class:"right-space" do
				%i.mi.md-18 book
				Cursos
			=link_to "#",class:"right-space" do
				%i.mi.md-18 message
				Mensajes
		=grid xs:6, md:1,class:"text-right last-md" do
			%i.mi notifications
			%sub 2
		

app/views/partials/demos/_publish.haml
%input.form-control.full-width.no-padding{placeholder:"Publicar... ",style:"padding:0 1em !important"}